- name: copilot
  color: '0e8a16'
  description: Issues intended for the Copilot coding agent
- name: good first issue
  color: '7057ff'
  description: Small tasks for new contributors
- name: bug
  color: 'd73a4a'
  description: Something isn't working
- name: enhancement
  color: 'a2eeef'
  description: New feature or request
- name: documentation
  color: '0075ca'
  description: Improvements to documentation
